[package]
name = "rustServer"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1", features = ["full"]} #async lib
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"


[[bin]]
name = "rust-server"
path = "src/server.rs"

